config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "sessions", registrations: "registrations" } #, registrations: "registrations"

devise_scope :user do
  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end

  unauthenticated do
    root to: 'devise/sessions#new', as: :unauthenticated_root
  end
end

  get 'home/index' => 'home#index'
  post 'submited/choice', to: 'home#manage'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Add this validation to your User model
  #default_scope -> { where(status: 'active') }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


     before_action :configure_permitted_parameters, if: :devise_controller?

     protected

          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :status, :lastLogged)}

               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :status, :lastLogged)}
          end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.unscoped.all
  end

  def manage
    selected_user_ids = params[:user_ids]

    if params[:block]
      User.unscoped.where(id: selected_user_ids).update_all(status: "blocked")
      flash[:notice] = "Action was successful!"
      if selected_user_ids.map(&:to_i).include?(current_user.id)
        sign_out_and_redirect(current_user)
      else
        redirect_to home_index_path
      end
    elsif params[:delete]
      User.unscoped.where(id: selected_user_ids).destroy_all
      flash[:notice] = "Action was successful!"
      redirect_to home_index_path
    elsif params[:unblock]
      User.unscoped.where(id: selected_user_ids).update_all(status: "active")
      flash[:notice] = "Action was successful!"
      redirect_to home_index_path
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    build_resource(sign_up_params)

    # Add custom validation for name
    if resource.name =~ /[^a-z\s]/i
      resource.errors.add(:name, "cannot contain anything other than letters (A-z)")
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
      return
    end

    # Add custom validation for email
    if resource.email =~ /^\d+|[^a-zA-Z0-9@.]/
      resource.errors.add(:Email, "is invalid.")
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
      return
    end
    # if resource.email =~ /^\d+@|[^\w@]/
    #   resource.errors.add(:Email, "cannot have special characters such as !,#,$,% etc")
    #   clean_up_passwords resource
    #   set_minimum_password_length
    #   respond_with resource
    #   return
    # end

    if resource.save
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def create
    self.resource = warden.authenticate!(auth_options)
    # Add this conditional statement to check if the user's status is 'blocked'
    if resource.status == "blocked"
      set_flash_message!(:alert, :blocked)
      sign_out(resource_name) # Add this line to sign out the user
      redirect_to new_user_session_path # Add this line to redirect to the login page
    else
      set_flash_message!(:notice, :signed_in) if is_navigational_format? # Move this line inside the else block
      yield resource if block_given?
      respond_with resource, location: after_sign_in_path_for(resource)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header_buttons.html.erb
<div class="text-end">
  <% if user_signed_in? %>
  <div class="d-flex align-items-center">
    <div class="me-2 name-container"> <%= current_user.name %> </div>
    <%= button_to "Log-Out", destroy_user_session_path, method: :delete, class: "btn btn-warning" %>
  </div>
  <% else %>
    <%= button_to "Log in", new_user_session_path, class: "btn btn-outline-light me-2" %>
  <% end %>
</div>

app/views/home/_table.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <%= form_tag(submited_choice_path, method: :post) do %>
        <div class="d-flex justify-content-end">
          <%= submit_tag 'Block', name: 'block', class: 'btn btn-danger mr-2' %>
          <div class="mx-2"></div>
          <%= button_tag type: 'submit', name: 'delete' do %>
            <i class="fa fa-trash-o" style="font-size:24px"></i>
          <% end %>
          <div class="mx-2"></div>
          <%= button_tag type: 'submit', name: 'unblock', class: 'btn btn-success' do %>
            <i class="fa fa-unlock" style="font-size:24px"></i>
          <% end %>
          <div class="ml-2"></div>
        </div>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-12">
      <table class="table-users">
        <thead>
          <tr>
            <th><%= check_box_tag 'select_all', nil, false, id: 'selectAll' %></th>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Last Login Time</th>
            <th>Registration Time</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= check_box_tag 'user_ids[]', user.id, false, class: 'input[type=checkbox]' %></td>
              <td><%= user.id %></td>
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <td><%= user.current_sign_in_at %></td>
              <td><%= user.created_at %></td>
              <td><%= user.status %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <% end %>
    </div>
  </div>
</div>

<script>
$("#selectAll").click(function() {
  $("input[type=checkbox]").prop("checked", $(this).prop("checked"));
});

$("input[type=checkbox]").click(function() {
  if (!$(this).prop("checked")) {
    $("#selectAll").prop("checked", false);
  }
});

jackHarnerSig();
</script>

app/views/home/index.html.erb
<% if user_signed_in? %>  
  <%= render "home/table" %>
<% else %>
<div class = "flex-container">
  <div class="d-grid">
    <%= button_to "Log In", new_user_session_path, class: "btn btn-lg btn-primary"  %> 
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task4</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
      .table-users {
        padding: 0 15px;
      }
     .dropdown-toggle::after {
        border-top-color: #ffffff;
      }
            .table-users {
        border-collapse: collapse;
        width: 100%;
      }

      .table-users th,
      .table-users td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
      }

      .table-users th {
        background-color: #f2f2f2;
        font-weight: bold;
      }

      .table-users tr:nth-child(even) {
        background-color: #f2f2f2;
      }

      .table-users input[type=checkbox] {
        margin-right: 8px;
      }

      .table-users #selectAll {
        margin-right: 16px;
      }
      .container-md {
        padding: 0 20%;
      }
      .alert {
        padding: 20px;
        background-color: #f44336;
        color: white;
        opacity: 1;
        transition: opacity 0.6s;
        margin-bottom: 15px;
      }

      .alert.success {background-color: #04AA6D;}
      .alert.info {background-color: #2196F3;}
      .alert.warning {background-color: #ff9800;}

      .closebtn {
        margin-left: 15px;
        color: white;
        font-weight: bold;
        float: right;
        font-size: 22px;
        line-height: 20px;
        cursor: pointer;
        transition: 0.3s;
      }

      .closebtn:hover {
        color: black;
      }
      .flex-container {
        display: flex;
        flex-wrap: wrap;
        align-content: center;
        justify-content: center;
        height: 200px;
        border: 1px solid black;
      }

      .flex-item {
        flex: 1 0 200px;
        margin: 10px;
        background-color: lightgray;
        text-align: center;
        line-height: 200px;
      }
    </style>
  </head>

  <body>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><h2>Task - 4</h2></li>
        </ul>
        <%= render 'header_buttons' %>
      </div>
    </div>
  </header>
    <% if notice %>
        <div class="alert success">
          <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>  
          <%= notice %>
        </div>
    <% end %>
    <% if alert %>
      <div class="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
        <%= alert %>
      </div>
    <% end %>
    <div style="margin-bottom: 20px;"></div>
    <%= yield %>
    </body>
</html>